language: node_js
branches:
  only:
    - master
git:
  depth: 1
node_js:
  - '0.10'
env:
  - SASS_VERSION=3.3.4
before_script:
  - gem update --system
  - gem install sass -v $SASS_VERSION
  - gem install scss-lint
  - npm install -g grunt-cli
